appName: emailservice
replicasCount: 2
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.8.0
containerPort: 8080
servicePort: 8080
serviceType: ClusterIP
containerEnvVars: 
  - name: PORT
    value: "8080"
  - name: DISABLE_PROFILER
    value: "1"
# livenessProbe:
#   grpc:
#     port: 8080
#   periodSeconds: 5

# readinessProbe:
#   grpc:
#     port: 8080
#   periodSeconds: 5
memoryRequest: 64Mi
cpuRequest: 250m
memoryLimit: 128Mi
cpuLimit: 500m