apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName  }}
  labels:
    app: {{ .Values.appName  }}
spec:
  replicas: {{ .Values.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName  }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.appImage }}:{{ .Values.appVersion }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        volumeMounts:
          - name: {{ .Values.volumeName }}
            mountPath: {{ .Values.mountPath }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          requests:
            memory: {{ .Values.memoryRequest }}
            cpu: {{ .Values.cpuRequest }}
          limits:
            memory: {{ .Values.memoryLimit }}
            cpu: {{ .Values.cpuLimit }}
      volumes:
      - name: {{ .Values.volumeName }}
        emptyDir: {}