apiVersion: v1
kind: Service
metadata:
  name : {{ .Values.appName }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports: 
  - protocol: TCP 
    port: {{ .Values.servicePort }}
    target: {{ .Values.containerPort }}