apiVersion: apps/v1
kind: Deployment
metadata:
  name: js-app
  labels:
    app: js-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: js-app
  template:
    metadata:
      labels:
        app: js-app
    spec:
      imagePullSecrets: # this is the secret that we created in the previous step
        - name: docker-authenticate
      containers:
      - name: js-app
        image: 565393037799.dkr.ecr.us-west-1.amazonaws.com/js-app:1.0 # this is the image from Private Repo
        imagePullPolicy: Always # this will always pull the image from the repository
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: js-app-service
spec:
  selector:
    app: js-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
