apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec: 
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
    template:
      metadata:
        labels:
          app: {{ .Values.appName }}
          spec: 
            containers:
            - name: {{ .Values.appName }}
              image: {{ .Values.appImage }}:{{ .Values.appVersion }}
              ports:
              - containerPort: {{ .Values.containerPort }}
              livenessProbe:
                {{ -toYaml .Values.livenessProbe | nindent 12 }} # toYaml is a function that converts the livenessProbe to yaml format
              readinessProbe:
                {{.Values.readinessProbe }}
              resources:
                requests: 
                  memory: {{ .Values.memoryRequest }}
                  cpu: {{ .Values.cpuRequest }}
                limits:
                  memory: {{ .Values.memoryLimit }}
                  cpu: {{ .Values.cpuLimit }}
              env: 
              {{ -range .Values.containerEnvVars }}
              - name: {{ .key }}
                value: {{ .value | quote }}
              {{ -end }}                
